api/urls.py
from django.urls import path
from rest_framework import routers

from .viewsets import ElementViewSet, CategoryViewSet, TypeViewSet, CommentViewSet

route = routers.SimpleRouter()
route.register('element',ElementViewSet)
route.register('category',CategoryViewSet)
route.register('type',TypeViewSet)
route.register('comment',CommentViewSet)

urlpatterns = route.urls

comments/urls.py
from django.urls import path
from . import views

app_name='comments'
urlpatterns = [
    path('add', views.add, name='add'),
    path('', views.index, name='index'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete')
]

elements/urls.py
from django.urls import path
from . import views

app_name='elements'
urlpatterns = [
    path('add', views.add, name='add'),
    path('', views.index, name='index'),
 
]

"""path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('', views.index, name='index')"""

mystore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls')),
    path('elements/', include('elements.urls')),
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

comments/models.py
from django.db import models

from elements.models import Element

# Create your models here.
class Comment(models.Model):
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    element = models.ForeignKey(Element, related_name='comments', on_delete=models.CASCADE, null=True)
 
    def __str__(self):
        return 'Comentario #{}'.format(self.id)

elements/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title

class Type(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title

class Element(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10,decimal_places=2, default=0.0) # 12345678.10
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

comments/forms.py
from django.forms import ModelForm, Textarea

from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
 

elements/forms.py
from django import forms
from django.core.validators import MinLengthValidator,EmailValidator
from .models import Category, Element, Type

class ElementForm(forms.Form):

    title = forms.CharField(label="Título", max_length=255, min_length=3, validators=[MinLengthValidator(10, message='Muy corto! (minino %(limit_value)d) actual %(show_value)d ')]  ) 
    description = forms.CharField(label='Descripción', initial='Tu increible post por aquí', widget=forms.Textarea, validators=[MinLengthValidator(2, message='Muy corto! (minino %(limit_value)d) actual %(show_value)d ')] )
    price = forms.DecimalField(label="Precio", required=False, max_digits=5, decimal_places=2)    
    type = forms.ModelChoiceField(label='Tipo', queryset=Type.objects.all(), initial=2)
    category = forms.ModelChoiceField(label='Categoría', queryset=Category.objects.all())

api/views.py
from django.shortcuts import render

# Create your views here.

comments/views.py
from .models import Comment
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .forms import CommentForm

# Create your views here.


def add(request):
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()
            return redirect('comments:index')
    else:
        form = CommentForm()

    return render(request,'comments/add.html',{'form':form})


def index(request):
    print(Comment.objects.get(pk=1))
    comments = Comment.objects.all()
    paginator = Paginator(comments,2)

    page_number = request.GET.get('page')
    comments_page = paginator.get_page(page_number)
    return render(request,'comments/index.html',{'comments':comments_page})


def update(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    #comment = Comment.objects.get(pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            form.save()
            return redirect('comments:index')
    else:
        form = CommentForm(instance=comment)

    return render(request,'comments/add.html',{'form':form, 'comment': comment})

def delete(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.method == 'POST':
        comment.delete()
    return redirect('comments:index')

elements/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator

from .models import Element
from .forms import ElementForm

# Create your views here.

def add(request):
    if request.method == 'POST':
        form = ElementForm(request.POST)
        if form.is_valid():
            element = Element()
            element.title = form.cleaned_data['title']
            element.description = form.cleaned_data['description']
            element.price = form.cleaned_data['price']
            element.category = form.cleaned_data['category']
            element.type = form.cleaned_data['type']
            element.save()
            return redirect('elements:index')
    else:
        form = ElementForm()

    return render(request,'element/add.html',{'form':form})

def index(request):
    elements = Element.objects.all()
    paginator = Paginator(elements,10)

    page_number = request.GET.get('page')

    return render(request,'element/index.html',{'elements':paginator.get_page(page_number)})

comments/templates/comments/add.html
{% extends "base.html" %}

{% block content %}
 <h1>Página para agregar</h1>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Enviar">
        </form>
{% endblock %}

comments/templates/comments/index.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado</title>
</head>

<body>
    <div style="width: 200px">
        {% for c in comments %}
        <div style="margin-top: 10px; border: 1px solid;">
            <p>{{ c.text }}</p>
            <hr>
            <p>{{ c.date_posted }}</p>
            <a href="{% url 'comments:update' c.id %}">Editar</a>
            <form action="{% url 'comments:delete' c.id %}" method="post">
                {% csrf_token %}
                <button type="submit">Borrar</button>
            </form>
        </div>
        {% endfor %}

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center mt-3">

                {% if comments.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ comments.previous_page_number }}">prev</a>
                </li>
                {% endif %}

                {% for i in comments.paginator.page_range %}

                {% if i == comments.number %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %}



                {% endfor %}

                {% if comments.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ comments.next_page_number }}">next</a>
                </li>
                {% endif %}

            </ul>
        </nav>

    </div>
</body>

</html>

comments/templates/comments/update.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
    
        <h1>Página para agregar</h1>
        <form action="{% url 'comments:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Enviar">
        </form>
    </body>
</html>

elements/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
    <body>
        <div class="container my-3">
            {% block content %}

            {% endblock %}
        </div>
    </body>
</html>

elements/templates/element/add.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

{% include "partials/errors-form.html" %}

<form action="{% url 'elements:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar">
</form>
{% endblock %}

elements/templates/element/index.html
{% extends "base.html" %}
{% block content %}
    {% for e in elements %}
        <table>
            <tr>
                <th>Título</th>
                <th>Categoría</th>
                <th>Tipo</th>
                <th>Precio</th>
                <th>Fecha</th>
                <th>Acciones</th>
            </tr>
            <tr>
                <td>{{ e.title }}</td>
                <td>{{ e.category.title }}</td>
                <td>{{ e.type }}</td>
                <td>{{ e.price }}</td>
                <td>{{ e.created }}</td>
            </tr>
        </table>
    {% endfor %}
    {% include 'partials/pagination.html' with page_obj=elements %}
{% endblock %}

elements/templates/partials/errors-form.html
{% if form.errors %}
    <br>
    {% for field in form  %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.name }}:</strong> {{ error }}
        </div>
    {% endfor %}
{% endfor %}
{% endif %}

elements/templates/partials/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center mt-3">

        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
            </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}

            {% if i == page_obj.number %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
            

            
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
            </li>
        {% endif %}

  </ul>
</nav>